version: '3'
services:
  file-server:
    build:
      context: .
    image: simple-file-server
    ports:
      - "8888:80"
    volumes:
      - ../performance_tests:/usr/share/nginx/html
    network_mode: bridge